package cn.chitanda.music.http.bean

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class PlaylistDetail(
    override val code: Int,
    override val message: String?,
    override val msg: String?,
    @Json(name = "playlist")
    override val data: Data?,
) : BaseJson<PlaylistDetail.Data?>() {
    @JsonClass(generateAdapter = true)
    data class Data(
        @Json(name = "adType")
        val adType: Long?,
        @Json(name = "backgroundCoverId")
        val backgroundCoverId: Long?,
        @Json(name = "backgroundCoverUrl")
        val backgroundCoverUrl: Any?,
        @Json(name = "cloudTrackCount")
        val cloudTrackCount: Long?,
        @Json(name = "commentCount")
        val commentCount: Long?,
        @Json(name = "commentThreadId")
        val commentThreadId: String?,
        @Json(name = "coverImgId")
        val coverImgId: Long?,
        @Json(name = "coverImgId_str")
        val coverImgIdStr: String?,
        @Json(name = "coverImgUrl")
        val coverImgUrl: String?,
        @Json(name = "createTime")
        val createTime: Long?,
        @Json(name = "creator")
        val creator: UserProfile.Data?,
        @Json(name = "description")
        val description: String?,
        @Json(name = "englishTitle")
        val englishTitle: Any?,
        @Json(name = "highQuality")
        val highQuality: Boolean?,
        @Json(name = "historySharedUsers")
        val historySharedUsers: Any?,
        @Json(name = "id")
        val id: Long?,
        @Json(name = "name")
        val name: String?,
        @Json(name = "newImported")
        val newImported: Boolean?,
        @Json(name = "officialPlaylistType")
        val officialPlaylistType: Any?,
        @Json(name = "opRecommend")
        val opRecommend: Boolean?,
        @Json(name = "ordered")
        val ordered: Boolean?,
        @Json(name = "playCount")
        val playCount: Long?,
        @Json(name = "privacy")
        val privacy: Long?,
        @Json(name = "remixVideo")
        val remixVideo: Any?,
        @Json(name = "shareCount")
        val shareCount: Long?,
        @Json(name = "sharedUsers")
        val sharedUsers: Any?,
        @Json(name = "specialType")
        val specialType: Long?,
        @Json(name = "status")
        val status: Long?,
        @Json(name = "subscribed")
        val subscribed: Boolean?,
        @Json(name = "subscribedCount")
        val subscribedCount: Long?,
        @Json(name = "subscribers")
        val subscribers: List<Any?>?,
        @Json(name = "tags")
        val tags: List<Any?>?,
        @Json(name = "titleImage")
        val titleImage: Long?,
        @Json(name = "titleImageUrl")
        val titleImageUrl: Any?,
        @Json(name = "trackCount")
        val trackCount: Long?,
        @Json(name = "trackIds")
        val trackIds: List<TrackId?>?,
        @Json(name = "trackNumberUpdateTime")
        val trackNumberUpdateTime: Long?,
        @Json(name = "trackUpdateTime")
        val trackUpdateTime: Long?,
        @Json(name = "tracks")
        val tracks: List<Track?>?,
        @Json(name = "updateFrequency")
        val updateFrequency: Any?,
        @Json(name = "updateTime")
        val updateTime: Long?,
        @Json(name = "userId")
        val userId: Long?,
        @Json(name = "videoIds")
        val videoIds: Any?,
        @Json(name = "videos")
        val videos: Any?
    ) {
        @JsonClass(generateAdapter = true)
        data class Creator(
            @Json(name = "accountStatus")
            val accountStatus: Long?,
            @Json(name = "anchor")
            val anchor: Boolean?,
            @Json(name = "authStatus")
            val authStatus: Long?,
            @Json(name = "authenticationTypes")
            val authenticationTypes: Long?,
            @Json(name = "authority")
            val authority: Long?,
            @Json(name = "avatarDetail")
            val avatarDetail: Any?,
            @Json(name = "avatarImgId")
            val avatarImgId: Long?,
            @Json(name = "avatarUrl")
            val avatarUrl: String?,
            @Json(name = "backgroundImgId")
            val backgroundImgId: Long?,
            @Json(name = "backgroundImgIdStr")
            val backgroundImgIdStr: String?,
            @Json(name = "backgroundUrl")
            val backgroundUrl: String?,
            @Json(name = "birthday")
            val birthday: Long?,
            @Json(name = "city")
            val city: Long?,
            @Json(name = "defaultAvatar")
            val defaultAvatar: Boolean?,
            @Json(name = "description")
            val description: String?,
            @Json(name = "detailDescription")
            val detailDescription: String?,
            @Json(name = "djStatus")
            val djStatus: Long?,
            @Json(name = "expertTags")
            val expertTags: Any?,
            @Json(name = "experts")
            val experts: Any?,
            @Json(name = "followed")
            val followed: Boolean?,
            @Json(name = "gender")
            val gender: Long?,
            @Json(name = "mutual")
            val mutual: Boolean?,
            @Json(name = "nickname")
            val nickname: String?,
            @Json(name = "province")
            val province: Long?,
            @Json(name = "remarkName")
            val remarkName: Any?,
            @Json(name = "signature")
            val signature: String?,
            @Json(name = "userId")
            val userId: Long?,
            @Json(name = "userType")
            val userType: Long?,
            @Json(name = "vipType")
            val vipType: Long?
        )

        @JsonClass(generateAdapter = true)
        data class TrackId(
            @Json(name = "alg")
            val alg: Any?,
            @Json(name = "at")
            val at: Long?,
            @Json(name = "id")
            val id: Long?,
            @Json(name = "rcmdReason")
            val rcmdReason: String?,
            @Json(name = "t")
            val t: Long?,
            @Json(name = "uid")
            val uid: Long?,
            @Json(name = "v")
            val v: Long?
        )

        @JsonClass(generateAdapter = true)
        data class Track(
            @Json(name = "a")
            val a: Any?,
            @Json(name = "al")
            val al: Al?,
            @Json(name = "alia")
            val alia: List<String?>?,
            @Json(name = "ar")
            val ar: List<Ar?>?,
            @Json(name = "cd")
            val cd: String?,
            @Json(name = "cf")
            val cf: String?,
            @Json(name = "copyright")
            val copyright: Long?,
            @Json(name = "cp")
            val cp: Long?,
            @Json(name = "crbt")
            val crbt: Any?,
            @Json(name = "djId")
            val djId: Long?,
            @Json(name = "dt")
            val dt: Long?,
            @Json(name = "fee")
            val fee: Long?,
            @Json(name = "ftype")
            val ftype: Long?,
            @Json(name = "h")
            val h: H?,
            @Json(name = "id")
            val id: Long?,
            @Json(name = "l")
            val l: L?,
            @Json(name = "m")
            val m: M?,
            @Json(name = "mark")
            val mark: Long?,
            @Json(name = "mst")
            val mst: Long?,
            @Json(name = "mv")
            val mv: Long?,
            @Json(name = "name")
            val name: String?,
            @Json(name = "no")
            val no: Long?,
            @Json(name = "noCopyrightRcmd")
            val noCopyrightRcmd: Any?,
            @Json(name = "originCoverType")
            val originCoverType: Long?,
            @Json(name = "originSongSimpleData")
            val originSongSimpleData: Any?,
            @Json(name = "pop")
            val pop: Long?,
            @Json(name = "pst")
            val pst: Long?,
            @Json(name = "publishTime")
            val publishTime: Long?,
            @Json(name = "rt")
            val rt: String?,
            @Json(name = "rtUrl")
            val rtUrl: Any?,
            @Json(name = "rtUrls")
            val rtUrls: List<Any?>?,
            @Json(name = "rtype")
            val rtype: Long?,
            @Json(name = "rurl")
            val rurl: Any?,
            @Json(name = "s_id")
            val sId: Long?,
            @Json(name = "single")
            val single: Long?,
            @Json(name = "st")
            val st: Long?,
            @Json(name = "t")
            val t: Long?,
            @Json(name = "tns")
            val tns: List<String?>?,
            @Json(name = "v")
            val v: Long?
        ) {
            @JsonClass(generateAdapter = true)
            data class Al(
                @Json(name = "id")
                val id: Long?,
                @Json(name = "name")
                val name: String?,
                @Json(name = "pic")
                val pic: Long?,
                @Json(name = "pic_str")
                val picStr: String?,
                @Json(name = "picUrl")
                val picUrl: String?,
                @Json(name = "tns")
                val tns: List<Any?>?
            )

            @JsonClass(generateAdapter = true)
            data class Ar(
                @Json(name = "alias")
                val alias: List<Any?>?,
                @Json(name = "id")
                val id: Long?,
                @Json(name = "name")
                val name: String?,
                @Json(name = "tns")
                val tns: List<Any?>?
            )

            @JsonClass(generateAdapter = true)
            data class H(
                @Json(name = "br")
                val br: Long?,
                @Json(name = "fid")
                val fid: Long?,
                @Json(name = "size")
                val size: Long?,
                @Json(name = "vd")
                val vd: Long?
            )

            @JsonClass(generateAdapter = true)
            data class L(
                @Json(name = "br")
                val br: Long?,
                @Json(name = "fid")
                val fid: Long?,
                @Json(name = "size")
                val size: Long?,
                @Json(name = "vd")
                val vd: Long?
            )

            @JsonClass(generateAdapter = true)
            data class M(
                @Json(name = "br")
                val br: Long?,
                @Json(name = "fid")
                val fid: Long?,
                @Json(name = "size")
                val size: Long?,
                @Json(name = "vd")
                val vd: Long?
            )
        }
    }

}